### ISSUE TITLE
Grid Beam

### ISSUE THREAD

**Issue by ahdinosaur** [villagekit/replicad-models#29]
a 3d printable grid beam, with hexagon holes. for 10mm, 20mm, and 40mm sizes.

for larger sizes, can try to imagine a "hollow" beam, with a triangle truss.

**Comment by hkienle** [comment]
Can you explain the rationale for using hexagon holes? I am puzzled how this is supposed to work. Thanks!

**Comment by ahdinosaur** [comment]
Oh hi @hkienle, didn't notice your comment until now. The rationale for hexagon holes is to be easier to print on any 3d printer without supports. A normal circle, when printed horizontally, becomes an overhang at the top. See [horiholes](https://hydraraptor.blogspot.com/2020/07/horiholes-2.html). A hexagon is just an easy way to avoid this problem, without needing to come up with a truncated teardrop solution, and they work at any angle, no matter how you align the design when printing, plus I think they look cool. In practice however, my Prusa i3 has no trouble printing circular holes, but I still like hexagons. Does that make sense? Thanks for asking. 💜

**Comment by hkienle** [comment]
Thanks for the detailed information, makes perfect sense now! :)
